services:
  openai-tts:
    build:
      context: .
      dockerfile: ./services/api-backend/openai-tts/Dockerfile.dev
    volumes:
      - ./services/api-backend/services/tts_service_openai.py:/app/tts_service_openai.py
      - /app/__pycache__
    command: uvicorn tts_service_openai:app --host 0.0.0.0 --port 5002 --reload

  eloquence-agent-v1:
    build:
      context: .
      dockerfile: ./services/api-backend/Dockerfile.agent.dev
    volumes:
      # On monte le dossier qui contient le code de l'agent
      - ./services/api-backend:/app
      - /app/__pycache__
    # La commande utilise watchfiles pour relancer le script Python à chaque modification
    # Le `.` surveille le répertoire courant du conteneur, qui est /app
    # Utilise la version que nous avons corrigée
    command: >
      sh -c "watchfiles 'python -u services/real_time_voice_agent_force_audio_fixed.py dev' ."