services:
  redis:
    image: redis:7-alpine
    restart: on-failure:5
    ports:
      - "6379:6379"
    networks:
      - eloquence-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data

  vosk-stt:
    build:
      context: ./services/vosk-stt-analysis
      dockerfile: Dockerfile
    image: eloquence/vosk-stt:latest
    restart: unless-stopped
    ports:
      - "8002:8002"
    networks:
      - eloquence-network
    volumes:
      - vosk-models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mistral-conversation:
    build:
      context: ./services/mistral-conversation
      dockerfile: Dockerfile
    image: eloquence/mistral-conversation:latest
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - eloquence-network
    env_file:
      - .env
    environment:
      - SCALEWAY_MISTRAL_URL=${SCALEWAY_MISTRAL_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MISTRAL_MODEL=${MISTRAL_MODEL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # === LIVEKIT SERVICES (Architecture Moderne) ===
  livekit-server:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    ports:
      - "7880:7880"    # WebSocket
      - "7881:7881"    # TCP fallback
      - "40000-40100:40000-40100/udp"  # RTC traffic
    networks:
      - eloquence-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7880/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - "LIVEKIT_KEYS=devkey: devsecret123456789abcdef0123456789abcdef"
      - LIVEKIT_LOG_LEVEL=info
      - LIVEKIT_RTC_TCP_PORT=7881
      - LIVEKIT_RTC_PORT_RANGE_START=40000
      - LIVEKIT_RTC_PORT_RANGE_END=40100
      - LIVEKIT_REDIS_HOST=redis
      - LIVEKIT_REDIS_PORT=6379

  livekit-token-service:
    build:
      context: ./services/livekit-server
      dockerfile: Dockerfile
    image: eloquence/livekit-token-service:latest
    restart: unless-stopped
    ports:
      - "8004:8004"
    networks:
      - eloquence-network
    env_file:
      - .env
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devsecret123456789abcdef0123456789abcdef
      - LIVEKIT_URL=ws://livekit-server:7880
    depends_on:
      livekit-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  livekit-agent:
    build:
      context: ./services/livekit-agent
      dockerfile: Dockerfile
    image: eloquence/livekit-agent:latest
    restart: unless-stopped
    networks:
      - eloquence-network
    env_file:
      - .env
    environment:
      - LIVEKIT_URL=ws://livekit-server:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devsecret123456789abcdef0123456789abcdef
      - LIVEKIT_ROOM=confidence_boost_default
      - VOSK_SERVICE_URL=http://vosk-stt:8002
      - MISTRAL_BASE_URL=${SCALEWAY_MISTRAL_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      livekit-server:
        condition: service_healthy
      livekit-token-service:
        condition: service_healthy
      mistral-conversation:
        condition: service_healthy
      vosk-stt:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  eloquence-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  vosk-models:
    driver: local
