# Configuration par défaut - Services de base
include:
  - docker/compose/docker-compose.base.yml

# Pour activer le système multi-agents, utiliser :
# docker compose -f docker-compose.yml -f docker/compose/docker-compose.multiagent.yml up -d
