name: eloquence_2_0
description: Application de coaching vocal pour améliorer l'expression orale
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  provider: ^6.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  path_provider: ^2.0.15
  http: ^1.0.0
  supabase_flutter: ^2.0.0
  
  # Packages audio pour la conversation vocale en temps réel
  audio_waveforms: ^1.0.4
  just_audio: ^0.9.36
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  
  # UI et navigation
  intl: ^0.18.1
  flutter_animate: ^4.1.1+1
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.4.0
  go_router: ^10.0.0
  logger: ^2.0.2
  
  # Communication réseau
  web_socket_channel: ^2.4.0
  
  # LiveKit et WebRTC - Mise à jour vers les dernières versions
  livekit_client: ^2.4.8
  flutter_webrtc: ^0.14.2
  
  # Utilitaires
  flutter_dotenv: ^5.1.0
  device_info_plus: ^11.5.0
  jwt_decoder: ^2.0.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.3.3
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.22.0
  bloc_test: ^9.1.1
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/orators/
  
  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBold.ttf
          weight: 600
    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600