// Mocks generated by Mockito 5.4.6 from annotations
// in eloquence_2_0/test/confidence_boost_livekit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i9;
import 'dart:ui' as _i10;

import 'package:eloquence_2_0/data/models/scenario_model.dart' as _i7;
import 'package:eloquence_2_0/data/models/session_model.dart' as _i2;
import 'package:eloquence_2_0/data/services/api_service.dart' as _i4;
import 'package:eloquence_2_0/src/services/clean_livekit_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:web_socket_channel/web_socket_channel.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSessionModel_0 extends _i1.SmartFake implements _i2.SessionModel {
  _FakeSessionModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebSocketChannel_1 extends _i1.SmartFake
    implements _i3.WebSocketChannel {
  _FakeWebSocketChannel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i6.Future<List<_i7.ScenarioModel>> getScenarios({
    String? type,
    String? difficulty,
    String? language = 'fr',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScenarios,
          [],
          {
            #type: type,
            #difficulty: difficulty,
            #language: language,
          },
        ),
        returnValue:
            _i6.Future<List<_i7.ScenarioModel>>.value(<_i7.ScenarioModel>[]),
      ) as _i6.Future<List<_i7.ScenarioModel>>);

  @override
  _i6.Future<_i7.ScenarioModel?> getScenario(String? scenarioId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScenario,
          [scenarioId],
        ),
        returnValue: _i6.Future<_i7.ScenarioModel?>.value(),
      ) as _i6.Future<_i7.ScenarioModel?>);

  @override
  bool isApiAuthError(dynamic error) => (super.noSuchMethod(
        Invocation.method(
          #isApiAuthError,
          [error],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i2.SessionModel> startSession(
    String? scenarioId,
    String? userId, {
    String? language = 'fr',
    String? goal,
    String? agentProfileId,
    bool? isMultiAgent = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [
            scenarioId,
            userId,
          ],
          {
            #language: language,
            #goal: goal,
            #agentProfileId: agentProfileId,
            #isMultiAgent: isMultiAgent,
          },
        ),
        returnValue: _i6.Future<_i2.SessionModel>.value(_FakeSessionModel_0(
          this,
          Invocation.method(
            #startSession,
            [
              scenarioId,
              userId,
            ],
            {
              #language: language,
              #goal: goal,
              #agentProfileId: agentProfileId,
              #isMultiAgent: isMultiAgent,
            },
          ),
        )),
      ) as _i6.Future<_i2.SessionModel>);

  @override
  _i6.Future<_i3.WebSocketChannel> connectWebSocket(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectWebSocket,
          [sessionId],
        ),
        returnValue:
            _i6.Future<_i3.WebSocketChannel>.value(_FakeWebSocketChannel_1(
          this,
          Invocation.method(
            #connectWebSocket,
            [sessionId],
          ),
        )),
      ) as _i6.Future<_i3.WebSocketChannel>);

  @override
  _i6.Future<bool> endSession(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #endSession,
          [sessionId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<String> transcribeAudio(String? audioFilePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeAudio,
          [audioFilePath],
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #transcribeAudio,
            [audioFilePath],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> generateResponse(String? prompt) => (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [prompt],
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [prompt],
          ),
        )),
      ) as _i6.Future<String>);
}

/// A class which mocks [CleanLiveKitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCleanLiveKitService extends _i1.Mock
    implements _i8.CleanLiveKitService {
  MockCleanLiveKitService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<_i9.Uint8List> get onAudioReceivedStream => (super.noSuchMethod(
        Invocation.getter(#onAudioReceivedStream),
        returnValue: _i6.Stream<_i9.Uint8List>.empty(),
      ) as _i6.Stream<_i9.Uint8List>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<bool> connect(
    String? url,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            url,
            token,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> publishMyAudio() => (super.noSuchMethod(
        Invocation.method(
          #publishMyAudio,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> unpublishMyAudio() => (super.noSuchMethod(
        Invocation.method(
          #unpublishMyAudio,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
