services:
  prometheus:
    image: prom/prometheus:latest
    container_name: eloquence-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - eloquence-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: eloquence-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ../../monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../../monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - eloquence-network
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:

networks:
  eloquence-network:
    driver: bridge

