services:
  redis:
    image: redis:7-alpine
    restart: on-failure:5
    ports:
      - "6379:6379"
    networks:
      - eloquence-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data

  vosk-stt:
    build:
      context: ../../services/vosk-stt-analysis
      dockerfile: Dockerfile
    image: eloquence/vosk-stt:latest
    restart: unless-stopped
    # ports exposés non nécessaires pour la com inter-containers
    networks:
      - eloquence-network
    volumes:
      - vosk-models:/app/models
      - ../../logs:/app/logs
    environment:
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mistral-conversation:
    build:
      context: ../../services/mistral-conversation
      dockerfile: Dockerfile
    image: eloquence/mistral-conversation:latest
    restart: unless-stopped
    # ports exposés non nécessaires pour la com inter-containers
    networks:
      - eloquence-network
    # env_file supprimé pour éviter dépendance à un .env local
    environment:
      - SCALEWAY_MISTRAL_URL=${MISTRAL_BASE_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MISTRAL_MODEL=${MISTRAL_MODEL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # === LIVEKIT SERVICES (Architecture Moderne) ===
  livekit-server:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    ports:
      - "8780:7880"    # WebSocket (port externe custom)
      - "40000-40100:40000-40100/udp"  # RTC traffic
    networks:
      - eloquence-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7880/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - "LIVEKIT_KEYS=devkey: devsecret123456789abcdef0123456789abcdef"
      - LIVEKIT_LOG_LEVEL=info
      - LIVEKIT_RTC_TCP_PORT=7881
      - LIVEKIT_RTC_PORT_RANGE_START=40000
      - LIVEKIT_RTC_PORT_RANGE_END=40100
      - LIVEKIT_REDIS_HOST=redis
      - LIVEKIT_REDIS_PORT=6379
      - LIVEKIT_ADVERTISED_IP=${HOST_LAN_IP}

  livekit-token-service:
    build:
      context: ../../services/livekit-server
      dockerfile: Dockerfile
    image: eloquence/livekit-token-service:latest
    restart: unless-stopped
    ports:
      - "8804:8004"
    networks:
      - eloquence-network
    # env_file supprimé pour éviter dépendance à un .env local
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devsecret123456789abcdef0123456789abcdef
      - LIVEKIT_URL=ws://192.168.1.44:8780
    depends_on:
      livekit-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  

  eloquence-exercises-api:
    build:
      context: ../../services/eloquence-exercises-api
      dockerfile: Dockerfile
    image: eloquence/exercises-api:latest
    restart: unless-stopped
    # ports exposés non nécessaires pour la com inter-containers
    networks:
      - eloquence-network
    # env_file supprimé pour éviter dépendance à un .env local
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LIVEKIT_URL=ws://livekit-server:7880
      - TOKEN_SERVICE_URL=http://livekit-token-service:8004
      - VOSK_SERVICE_URL=http://vosk-stt:8002
    depends_on:
      redis:
        condition: service_healthy
      livekit-server:
        condition: service_healthy
      livekit-token-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  eloquence-network:
    driver: bridge
  eloquence_default:
    driver: bridge

volumes:
  redis-data:
    driver: local
  vosk-models:
    driver: local
